dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U pytest-cov matplotlib pandas numpy jsondiff
  - python setup.py install
# command to run tests
script:
  - pytest --cov=fairgraph