name: Mirror to EBRAINS Gitlab

on:
  push:
    branches: [ master ]

jobs:
  to_ebrains:
    runs-on: ubuntu-latest
    steps:
      - name: syncmaster
        uses: wei/git-sync@v3
        with:
          source_repo: "HumanBrainProject/fairgraph"
          source_branch: "master"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/data-services/fairgraph.git"
          destination_branch: "main"
      - name: synctags
        uses: wei/git-sync@v3
        with:
          source_repo: "HumanBrainProject/fairgraph"
          source_branch: "refs/tags/*"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/data-services/fairgraph.git"
          destination_branch: "refs/tags/*"
